jdk: openjdk8
cache:
  directories:
    - ~/data/downloads
services:
- docker
install:
- curl -fsSL get.nextflow.io | bash
jobs:
  include:
    - stage: "Data Download"
      script:
      - if [ -d ~/data/downloads/exemplar-001 ]; then
          echo "Using cached exemplar-001 download";
        else
          ./nextflow exemplar.nf --name exemplar-001 --path ~/data/downloads;
        fi
      - if [ -d ~/data/downloads/exemplar-002 ]; then
          echo "Using cached exemplar-002 download";
        else
          ./nextflow exemplar.nf --name exemplar-002 --path ~/data/downloads;
        fi
    - stage: "Exemplars"
      name: "Exemplar-001"
      script:
      - cp -r ~/data/downloads/exemplar-001 ~/data/
      - ./nextflow main.nf --in ~/data/exemplar-001 --probability-maps all
    - name: "Exemplar-001 step by step"
      script:
      - cp -r ~/data/downloads/exemplar-001 ~/data/exemplar-001-ss
      - ./nextflow main.nf --in ~/data/exemplar-001-ss --start-at registration --stop-at registration
      - ./nextflow main.nf --in ~/data/exemplar-001-ss --start-at probability-maps --stop-at probability-maps --probability-maps ilastik
      - ./nextflow main.nf --in ~/data/exemplar-001-ss --start-at segmentation --stop-at segmentation --probability-maps ilastik
      - ./nextflow main.nf --in ~/data/exemplar-001-ss --start-at probability-maps --stop-at probability-maps --probability-maps unmicst
      - ./nextflow main.nf --in ~/data/exemplar-001-ss --start-at segmentation --stop-at segmentation --probability-maps unmicst
    - name: "Exemplar-002"
      script:
      - cp -r ~/data/downloads/exemplar-002 ~/data/
      - travis_wait ./nextflow main.nf --in ~/data/exemplar-002 --tma --stop-at dearray
      - travis_wait ./nextflow main.nf --in ~/data/exemplar-002 --tma --start-at probability-maps --stop-at probability-maps --probability-maps ilastik
      - ./nextflow main.nf --in ~/data/exemplar-002 --tma --start-at segmentation --probability-maps ilastik
