jdk: openjdk8
cache:
  directories:
    - ~/data/downloads
services:
- docker
install:
- curl -fsSL get.nextflow.io | bash
jobs:
  include:
    - script: bash tests/exemplar-001.sh
    - script: bash tests/exemplar-002.sh
